version: "3"

services:
  keycloak:
    container_name: keycloak.test
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    entrypoint: >
      /opt/keycloak/bin/kc.sh start-dev
      --import-realm
      --http-port=8080
      --hostname-strict=false
      --proxy=edge
