name: Publish to npm

on:
  push:
    branches:
      - master # or any branch you want to trigger the publish

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        continue-on-error: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
        continue-on-error: false

      - name: Install dependencies
        run: npm install
        continue-on-error: false

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Build the project
        run: npm run build
        continue-on-error: false

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: false
